---
- name: Check if Ubuntu ISO exists 
  stat: 
    path: "/var/lib/vz/template/iso/ubuntu-24.04-live-server-amd64.iso" 
  register: iso_file 

- name: Download Ubuntu ISO 
  get_url: 
    url: "https://releases.ubuntu.com/24.04/ubuntu-24.04-live-server-amd64.iso" 
    dest: "/var/lib/vz/template/iso/ubuntu-24.04-live-server-amd64.iso" 
  when: not iso_file.stat.exists

# tasks file for prxmx_vm_2024

- name: Create VM in Proxmox VE
  proxmox_kvm:
    api_user: "root"
    api_password: "ixelles1050"
    api_host: "pve-pxs-sm2u-r5-33"
    node: "pve-pxs-sm2u-r5-33"
    vmid: 100
    name: "ubuntu_vm"
    memory: 2048
    cores: 2
    scsi0: "local-lvm:50" 
    scsi1: "local-lvm:30" 
    scsi2: "local-lvm:20"
    net0: "virtio,bridge=vmbr0,tag=vlan-test"
    ostype: "l26"
    iso: "/var/lib/vz/template/iso/ubuntu-24.04-live-server-amd64.iso"
    state: present

- name: Disable Firewall
  ufw:
    state: disabled

- name: Install Nginx
  apt:
    name: nginx
    state: present

- name: Install PostgreSQL
  apt:
    name: postgresql
    state: present

- name: Install PHP
  apt:
    name: php
    state: present
