---


# tasks file for prxmx_vm_2024

- name: Create VM in Proxmox VE
  community.general.proxmox_kvm:
    api_user: "root"
    api_password: "ixelles1050"
    api_host: "pve-pxs-sm2u-r5-33"
    node: "pve-pxs-sm2u-r5-33"
    vmid: 100
    name: "my_vm"
    iso: "/var/lib/vz/template/iso/ubuntu-24.04.1-live-server-amd64.iso"
    net:
      - model: virtio
        bridge: vmbr0
    scsi:
      - size: 50
        storage: local
        format: qcow2
    cores: 2
    memory: 2048
    ostype: "l26"
    boot: "c"
    state: "present"

